name: feature-branch
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run format:lint:lib
      - name: Test
        run: npm run test:lib
      - name: Coverage
        run: npm run test:lib-coverage
      - name: Publish to coveralls
        uses: coverallsapp/github-action@v2.2.3
      - name: Build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SC }}
